services:
  fastapi:
    build: .
    # image: ${DOCKER_HUB_USERNAME}/fastapi-app:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: fastapi_app
    expose:
      - "8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
